Add MQTT encryption and authentication
wdoekes/pe32me162ir_pub pull request #2
Opened 2021-05-01 08:28 UTC by DigitalBrains1

Authentication is only allowed on encrypted connections to prevent
sending the password in plaintext.

Note: TLS is pretty hard on the small amount of RAM on an ESP8266. But it has been runnning fine for the last three-and-a-half days here with the current code.

2021-05-01 15:31 UTC, wdoekes requested changes
Thanks for the PR :)

2021-05-01 15:31 UTC, wdoekes commented on pe32me162ir_pub.ino
> +/* Use password authentication (only valid when MQTT_TLS is set) */
These should be moved to config.h so as not to disturb those who aren't using these.

2021-05-01 15:31 UTC, wdoekes commented on pe32me162ir_pub.ino
> +// if MQTT_TLS
Perhaps something like this:
```
//#define MQTT_TLS
#ifdef MQTT_TLS
const unsigned char mqtt_fingerprint[20] = ...
...
#endif
```

2021-05-01 16:02 UTC, DigitalBrains1 commented
Sure, I'm fine with that. I'll change it.

I do want to note I'm not a huge fan of the whole `config.h` construction. Rather than give users a complete project where they need to set a few switches and enter some details, there's a comment in the code instructing them to create a new file with a certain, exact structure which they will probably copy-paste from your code. Why not include the code? And for bonus points, split secret data from other configuration details. Perhaps something like [this](https://www.andreagrandi.it/2020/12/16/how-to-safely-store-arduino-secrets/). You could have a `config.h` included with the project, and an `arduino_secrets.h.example` file like that webpage mentions (the latter defining macro's, not variables!).

2021-05-02 13:31 UTC, wdoekes commented
I'm afraid I made collisions in this PR too.
:runner:

2021-05-09 14:52 UTC, wdoekes commented
This one is intentionally in Draft, yes? :angel:

2021-05-09 14:56 UTC, DigitalBrains1 commented
Yes, it needs the updated bogoduino which imports `cstdint`, and also, I had not tested this rebase yet. I simply pushed too early.

I currently don't have the time, though, so it'll be a while.

2021-05-09 15:58 UTC, wdoekes commented
Okay. Just checking :)

I committed the cstdint change in https://github.com/wdoekes/bogoduino/commit/9b7243066ce223e13b838b82a389285164036fdd just now.

2021-05-20 16:42 UTC, DigitalBrains1 commented
Having determined both that my problem was at the server end and how to fix that problem, I now am confident this branch runs stably. Unlike the server, it has kept going for more than 6 days.

2021-05-22 20:08 UTC, merged

2021-05-22 20:08 UTC, wdoekes commented
Nice :)

2021-05-22 20:14 UTC, DigitalBrains1 commented
Thanks :-)